# Requires AFHQ dataset folders to be combined into 1 class
DATA:
  name: "AFHQv2"
  img_size: 512
  num_classes: 3
MODEL:
  backbone: "stylegan3"
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  g_act_fn: "Auto"
  d_act_fn: "Auto"
  z_prior: "gaussian"
  z_dim: 512
  w_dim: 512
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  apply_g_ema: True
LOSS:
  adv_loss: "logistic"
  apply_r1_reg: True
  r1_lambda: 16.4
  r1_place: "outside_loop"
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  batch_size: 32
  g_lr: 0.0025
  d_lr: 0.002
  beta1: 0
  beta2: 0.99
  d_first: False
  g_updates_per_step: 1
  d_updates_per_step: 1
  total_steps: 781250
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.6
  ada_kimg: 500
  ada_interval: 4
STYLEGAN:
  stylegan3_cfg: "stylegan3-r"
  blur_init_sigma: 10
  g_reg_interval: 1
  d_reg_interval: 16
  mapping_network: 2
  style_mixing_p: 0
  g_ema_kimg: 10
  g_ema_rampup: 0.05
  apply_pl_reg: False
  pl_weight: 0
  d_architecture: "resnet"
  d_epilogue_mbstd_group_size: 4
