name: py37
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.16=hb2f20db_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-include=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.44=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.7.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.47.0=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - adamp==0.2.0
    - apex==0.1
    - appdirs==1.4.4
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.1
    - cachetools==4.0.0
    - chardet==3.0.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distlib==0.3.1
    - entrypoints==0.3
    - filelock==3.0.12
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - importlib-metadata==1.5.0
    - install==1.3.3
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.16.0
    - jinja2==2.11.1
    - jsonschema==3.2.0
    - jupyter-client==6.0.0
    - jupyter-core==4.6.3
    - markdown==3.2.1
    - markupsafe==1.1.1
    - minkowskiengine==0.4.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - notebook==6.0.3
    - oauthlib==3.1.0
    - open3d==0.9.0.0
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pip==20.2.2
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.3
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.5.2
    - pyrsistent==0.15.7
    - pyzmq==19.0.0
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.1.0
    - send2trash==1.5.0
    - style==1.1.0
    - tensorboard==2.1.1
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - update==0.0.1
    - urllib3==1.25.8
    - virtualenv==20.0.30
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==1.0.0
    - widgetsnbextension==3.5.1
    - zipp==3.1.0
prefix: /root/anaconda3/envs/py37

