DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [2]
  attn_d_loc: [1]
  z_dim: 80
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  adv_loss: "logistic"
OPTIMIZATION:
  total_steps: 400000
PRE:
  apply_rflip: False
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.6
  ada_kimg: 500
  ada_interval: 4
